### ISSUE TITLE
Prevent invalid squawks

### ISSUE THREAD

**Issue by A-Lawrence** [VATSIM-UK/web-squawk-gen#2]
Since squawks can only be 4 digits between 0 and 7 (as they're octal) it's important to prevent erroneous squawks being generated.

**Comment by atoff** [comment]
This shouldn't ever happen (as long as the squawk code data in the database is correct), but I will add a check for this.

**Comment by atoff** [comment]
Disregard the comment about it not happening, fix on the way

**Comment by A-Lawrence** [comment]
Thanks! Hadn't checked the database structure you were using.
