### ISSUE TITLE
Channel Islands Domestic Codes

### ISSUE THREAD

**Issue by atoff** [VATSIM-UK/web-squawk-gen#6]
As suggested via VATSIM UK Forums:

> 1201 - 1277    Channel Islands Domestic - These codes are used for IFR departures from the Channel Islands to the UK.

**Comment by trevorhannant** [comment]
Any progress on this?

**Comment by atoff** [comment]
Hi Trevor, not as yet due to other projects which have taken priority (namely Core)

Problem is that this would require adding another input field for the departure airport, which would require a change in code and make the web-based allocator somewhat less quick to use.

Looking forwards though, this will be incorporated when this is extended for our euroscope plugin (where the user doesn't need to type in the airports, and it would be a lot faster)

If I get some time though, I will try and get this incorporated somehow.
